name: Test Main Branch

on:
    pull_request:
        branches:
            - main
        types:
            - closed
jobs:
    Build_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: setup node js enviroment
              uses: actions/setup-node@v6
              with:
                  node-version: "22.21.0"

            - name: Run terminal commands
              run: |
                  echo "Hello from terminal"
                  pwd
                  ls -la
                  node -v
